version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  cache:
    image: redis:7
    ports: ["6379:6379"]
  api:
    build: ../apps/api
    env_file: ../.env
    depends_on: [db, cache, ai]
    ports: ["4000:4000", "4010:4010"]
  web:
    build: ../apps/web
    env_file: ../.env
    depends_on: [api]
    ports: ["3000:3000"]
  ai:
    build: ../apps/ai
    env_file: ../.env
    ports: ["8000:8000"]
volumes:
  pgdata:
