[project]
name = "codequest-ai"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["fastapi", "uvicorn", "pydantic"]
[project.scripts]
start = "uvicorn src.app:app --host 0.0.0.0 --port 8000"
